""" позволяет принудительно вызвать указанное исключение"""
raise Exception("Error..")
